project:
  type: book

book:
  title: "NOMBRE DE CURSO"
  author: "Brayan Cubides"
  repo-url: "https://github.com/bcubides-est/molde"
  repo-branch: main
  favicon: logo.png
  description: "Material del curso ---"
  url: "/molde/"
  page-navigation: true        # prev/next
  sidebar:
    tools:
    - icon: globe
      href: https://bcubides-est.github.io/website/
      text: "Ir a mi web"

    - icon: download
      href: 'javascript:window.print()'
      text: "Descargar (PDF)"
    logo: logo.png
    search: true    
  image: logo.png
  
  chapters:
    - index.qmd
    - CONTENIDO/Capitulo_Ejemplo.qmd

format:
  html:
    theme:
      light: cerulean #simplex 
      dark: cyborg
    css: custom.css
    code-fold: false
    toc-collapse: true  # Listas desplegables contraídas por defecto
    toc-depth: 2
    execute:
      output-dir: _book
    self-contained: false